name: Node CI
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: CI
      env:
        BAMBORA_API_KEY: ${{ secrets.BAMBORA_API_KEY }}
        MAILGUN_ACCESS_TOKEN: ${{ secrets.MAILGUN_ACCESS_TOKEN }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      run: |
        yarn install
        yarn lint
        yarn test
    - name: Lcov
      run: yarn lcov
    - name: Coveralls 
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        