name: Node CI
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Lint
      run: |
        yarn install
        yarn lint
    - name: Test
      env:
        BAMBORA_API_KEY: ${{ secrets.BAMBORA_API_KEY }}
        MAILGUN_ACCESS_TOKEN: ${{ secrets.MAILGUN_ACCESS_TOKEN }}
        MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
      run: yarn test
