name: Node CI
<<<<<<< HEAD
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
=======
on: [pull]
>>>>>>> 8bac54bbcccc7db8845122dbbf2041174f2e72b9
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: yarn test and publish
      run: |
        yarn install
        yarn lint
        yarn test:packages
        yarn test:integrations
