name: Node CI
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.2
    - name: yarn test and publish
      run: |
        yarn install
        yarn lint
        yarn test:packages
    - name: Coveralls 
      uses: coverallsapp/github-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}